# Generated by Django 5.0.4 on 2024-05-19 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0003_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='members_attending',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
