# Generated by Django 5.0.4 on 2024-05-19 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_booking_members_attending'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='approximate_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
